<?php
// Ten plik zawiera listę hostów dopuszczonych do wyświetlania tablicy.
// UWAGA!!! Lista musi składać się z pojedyńczych hostów. NIE MOŻNA WPROWADZAĆ ADRESÓW SIECI/PODSIECI!!!

	$hosts_allowed_operator = array ('192.168.0.180', '192.168.0.164', '192.168.0.178', '192.168.0.179', '192.168.0.21', '192.168.82.101', '192.168.82.102', '192.168.82.103', '192.168.71.134');	// tablica operatora
	$hosts_allowed_all = array ('192.168.0.180', '192.168.0.101', '192.168.64.102');		// wszystkie tablice
	$hosts_allowed_board = array ('192.168.64.31');	// lista dla tablic ściennych
?>
